name: communicatiehelper
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  whiteboard: ^0.0.1
  file_saver: ^0.1.0
  webview_flutter: ^3.0.4
  syncfusion_flutter_calendar: ^20.1.59
  intl: ^0.17.0
  syncfusion_localizations: ^20.1.59
  syncfusion_flutter_core: ^20.1.59
  google_maps_flutter: ^2.1.7
  geolocator: ^8.2.1
  http: ^0.13.4
  firebase_core: ^1.18.0
  cloud_firestore: ^3.1.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  drift_dev: ^1.6.0
  build_runner: ^2.1.10

flutter:
  uses-material-design: true
  assets:
    - images/calendar.png
    - images/camera.png
    - images/dairy.png
    - images/drawing.png
    - images/maps.png
    - images/news.png
    - images/photo.png
    - images/settings.png
    - images/socialmedia.png
    - images/symbols.png
    - images/user.png
    - images/videocall.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
