name: communicatiehelper
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  drift: ^1.6.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.0
  provider: ^6.0.3
  image_picker: ^0.8.5+3
  whiteboard: ^0.0.1
  image_gallery_saver: ^1.7.1
  file_saver: ^0.1.0
  gallery_saver: ^2.3.2
  photo_gallery: ^1.1.1
  webview_flutter: ^3.0.4
  add_2_calendar: ^2.1.3
  calendar_view: ^0.0.5
  syncfusion_flutter_calendar: ^20.1.59
  intl: ^0.17.0
  syncfusion_localizations: ^20.1.59
  syncfusion_flutter_core: ^20.1.59
  google_maps_flutter: ^2.1.7
  geolocator: ^8.2.1
  dio: ^4.0.6
  flutter_polyline_points: ^1.0.0
  location: ^4.4.0
  http: ^0.13.4
  shared_preferences: ^2.0.15
  table_calendar: ^3.0.6
  firebase_core: ^1.18.0
  cloud_firestore: ^3.1.18
  firebase_database: ^9.0.16



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  drift_dev: ^1.6.0
  build_runner: ^2.1.10

flutter:
  uses-material-design: true
  assets:
    - images/calendar.png
    - images/camera.png
    - images/dairy.png
    - images/drawing.png
    - images/maps.png
    - images/news.png
    - images/photo.png
    - images/settings.png
    - images/socialmedia.png
    - images/symbols.png
    - images/user.png
    - images/videocall.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
